name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  main:
    name: Nx Release - Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests (Affected)
        run: npx nx affected --target=test 
      - name: Run Project Release (Affected)
        run: npx nx affected --target=release
