name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  main:
    name: Nx Release - Main Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
    
      - name: Evaluate affected
        uses: leanix/nx-affected-dependencies-action@v0.2.1
        id: affected
        with:
          project: pathfinder
          base: ${{ github.sha }}~1
          head: ${{ github.sha }}

      - name: Run Unit Tests (Affected)
        if: steps.affected.outputs.isAffected == 'true'
        env:
          affectedDeps: ${{ steps.affected.outputs.affectedDeps }}
        run: npx nx run-many --target=test --projects=$affectedDeps

      - name: Run Releases (Affected)
        if: steps.affected.outputs.isAffected == 'true'
        env:
          affectedDeps: ${{ steps.affected.outputs.affectedDeps }}
        run: npx nx run-many --target=release --projects=$affectedDeps
